name: run-unit-tests
on: [push]

jobs:
  unit-test:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          python-version: "17"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Unit Tests
        run: |
          npm test

      - name: Set version
        run: |
          echo "PACKAGE_JSON_VERSION=$(cat src/manifest.json | jq --raw-output .version)" >> GITHUB_ENV
          echo "Version: ${PACKAGE_JSON_VERSION}"

      - name: Build dist
        run: |
          ./build.sh

      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_JSON_VERSION }}
          name: ${{ env.PACKAGE_JSON_VERSION }} (${{ github.sha }})
          body: Release notes needed...
          draft: true
          prerelease: false
          files: dist/cross-stitcher.zip