name: build-dist

on:
  workflow_run:
    workflows: ["run-unit-tests"]
    types:
      - completed

jobs:
  dist:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          python-version: "17"

      - name: Install dependencies
        run: |
          npm install

      - name: Build dist
        run: |
          ./build.sh

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/cross-stitcher.zip"
          token: ${{ secrets.GITHUB_TOKEN }}